import Navbar from "./Components/Navbar";
import "./globals.css";

export const metadata = {
  title: "Neora | Checkout",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-zinc-100">
        <div className="w-full max-w-[1600px] m-auto">{children}</div>
      </body>
    </html>
  );
}
