import Navbar from "./Components/Navbar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-zinc-100">
        <Navbar />
        <div className="w-full max-w-[1400px] m-auto px-10 py-8">
          {children}
        </div>
      </body>
    </html>
  );
}
